import type { Reel } from "./types.js";

// Placeholder clips (generated by scripts/make-demo-reels.sh). Barbers replace them
// by uploading real videos from the app.
const demo = (id: string, barberId: string, caption: string, daysAgo: number, likes: number): Reel => ({
  id,
  barberId,
  videoUrl: `/media/demo/${id}.mp4`,
  posterUrl: `/media/demo/${id}.jpg`,
  caption,
  likedBy: Array.from({ length: likes }, (_, i) => `demo-${i}`),
  createdAt: new Date(Date.UTC(2026, 8, 30 - daysAgo, 12)).toISOString(),
});

export const DEMO_REELS: Reel[] = [
  demo("r1", "b1", "Zero to skin fade in 25 minutes ✂️ #fade #berlin", 1, 342),
  demo("r2", "b1", "Beard sculpt + hot line-up. Book me, I come to you 🏠", 4, 198),
  demo("r3", "b2", "Textured crop with scissors only. Low maintenance, high style.", 2, 156),
  demo("r4", "b3", "Turkish hot towel shave — the full ritual 🔥", 3, 421),
  demo("r5", "b4", "The modern mullet, done right.", 5, 127),
  demo("r6", "b5", "360 waves check 🌊 Brushing routine in the caption", 1, 512),
  demo("r7", "b5", "Custom hair design — bring your idea", 6, 289),
  demo("r8", "b6", "Classic side part, Jermyn Street style.", 2, 173),
  demo("r9", "b8", "French crop, Amsterdam minimal.", 3, 144),
  demo("r10", "b9", "Luxury fade at your villa ✨", 2, 377),
  demo("r11", "b10", "Taper + waves in Brooklyn", 1, 265),
  demo("r12", "b11", "Pompadour with volume that lasts all day", 4, 208),
];
